name: Release CI

on:
  push:
    branches:
      - main

jobs:
  releaseOnNPM:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Publish on NPM registry
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
