name: Release CI

on:
  release:
    types: [published]

jobs:
  releaseOnNPM:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        run: npm install

      - name: run run build
        run: npm run build

      - name: npm publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
