name: Release CI

on:
  push:
    branches:
      - master

jobs:
  releaseOnNPM:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish on NPM registry
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
