name: Pull Request CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: npm intall
        run: npm install

      - name: run build
        run: npm run build

      - name: npm publish
        run: npm run publish
