name: New Tag

on:
  release:
    types: [published]

jobs:
  releaseOnNPM:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        run: npm install

      - name: run build
        run: npm run build

      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
