name: New Tag

on:
  create:
    tags:
      - '*'

jobs:
  releaseOnNPM:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: npm install
        run: npm install

      - name: run build
        run: npm run build

      - name: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag=latest
